### ISSUE TITLE
Update of SolR lead to missing texts in search results

### ISSUE THREAD

**Issue by jschirrmacher** [redlink-gmbh/chatpal-search#25]
We updated Solr to version 7.71 and experience missing texts in search results since then.
The user names and dates are shown.

<img width="566" alt="Bildschirmfoto 2019-04-03 um 16 30 43" src="https://user-images.githubusercontent.com/2821879/55608490-ddc9da80-577e-11e9-92bc-d581d7f7ed47.png">

The text is not included in the DDP messages, but I suppose they should be.

**Comment by ruKurz** [comment]
@tkurz could you please take a look at this?

**Comment by westei** [comment]
this Issue was reported in the wrong repository see https://github.com/chatpal/chatpal-search-solr-ext/pull/13 for the fix
