### ISSUE TITLE
Chatpal search does not work with Smarti 0.6.1

### ISSUE THREAD

**Issue by ruKurz** [redlink-gmbh/chatpal-search#3]
The results of Smarti 0.6.1 do not fit to ChatPal Search:

chatpal-search fails by executing:

`/packages/chatpal-search/server/service/search_service.js`

```
static alignResponse(result) {
  const docs = [];
  result.response.forEach(function(doc) {
    docs.push({
      type: doc.type,
      subtype: 'c',
      room: doc.meta_channel_id[0],
      id: doc.message_id,
      text: doc.message,
      highlight_text: result.highlighting[doc.id] ? result.highlighting[doc.id].message[0] : undefined,
      user: doc.user_id,
      date: doc.time
    });

    return {
      numFound: result.meta.numFound,
      start: result.meta.start,
      docs
    };
  }
});
```

The Smarti response of:
`http://localhost:8080/rocket/localhost/search?sort=time%20desc&fl=id,message_id,meta_channel_id,user_id,time,message,type&hl=true&hl.fl=message&df=message&q=braunschweig`

does not return the JSON-Format expected by chatpal search.
E.g. 

- `result.response` is undefined
- the requested return fields: id,message_id,meta_channel_id,user_id,time,message,type do not persist in the response of Smarti

Not quiet sure if this has to be solved within chatpal or within Smarti.

I also commented this in:
https://github.com/redlink-gmbh/smarti/issues/121

**Comment by tkurz** [comment]
Can you send me the results that is responded if you issue the query `http://localhost:8080/rocket/localhost/search?sort=time%20desc&fl=id,message_id,meta_channel_id,user_id,time,message,type&hl=true&hl.fl=message&df=message&q=braunschweig` directly to smarti?

**Comment by mrsimpson** [comment]
the endpoint for chatpal should be `/rocket/localhost/message-search`
